Feature/c feature extraction
humleflue/p6 pull request #63
Opened 2022-05-13 11:54 UTC by JacobToftgaardRasmussen

2022-05-14 06:49 UTC, humleflue requested changes
Looks good. I have put some comments for polishing. I love the tests! 😍

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +#include <stdio.h>
```suggestion
```

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +    double highestNumber = 0;
```suggestion
    int highestNumber = 0;
```

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +double getBiggestNumber(double axisArray[], int length){
```suggestion
int getBiggestAbsNumber(int axisArray[], int length){
```

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +    int negativeOrPositive = 1;
```suggestion
```

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +        double currentNumber = axisArray[i];
```suggestion
        int currentNumber = abs(axisArray[i]);
```
Implementer en abs funktion.

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +        }
```suggestion
    if (currentNumber > highestNumber) {
        highestNumber = currentNumber;
    }
```

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +double getSmallestNumber(double axisArray[], int length){
Abstract over biggest- and smallestNumber, as they are almost the same implementation. Maybe you can make an auxiliary function?

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +double absMean(double axisArray[], int length){
```suggestion
int absMean(int axisArray[], int length){
```

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +    double result = absSum(axisArray, length);
```suggestion
    int result = absSum(axisArray, length);
```

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +}
change double to int

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +        }
```suggestion
        result += abs(axisArray[i]);
```

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +    int i;
```suggestion
    int i, cur;
```

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +    double result = 0;
Change double to int

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/math.c
> +    double result = 0;
double -> int

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	double expected = -5;
This belongs in the arrange step

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	double expected = 5;
This belongs in the arrange step

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	CuAssertTrue(tc, expected == actual);
Use CuAssertIntEquals

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	double expected = -5;
this is arrange

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	CuAssertTrue(tc, expected == actual);
use CuAssertIntEquals

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	double expected = -1;
arrange

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	CuAssertTrue(tc, expected == actual);
CuAssertIntEquals

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	double expected = 1;
arrange

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	CuAssertTrue(tc, expected == actual);
CuAssertIntEquals

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	double expected = 1;
arrange

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	CuAssertTrue(tc, expected == actual);
CuAssertIntEquals

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	CuAssertTrue(tc, expected == actual);
CuAssertIntEquals

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	double expected = 2;
arrange

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	double expected = 2;
arrange
- you get the point, right? 😅

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	CuAssertTrue(tc, expected == actual);
CuAssertIntEquals

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/TransformTests.c
> +	double expectedZ[TIME_SERIES_VECTORS_AMOUNT] = {3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3};
int

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +    double numbers[TIME_SERIES_VECTORS_AMOUNT] = {-5,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3,-1,-2,-3};
int

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/MathTests.c
> +	double expected = -5;
and its an int

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/test/TransformTests.c
> +		CuAssertTrue(tc, expectedZ[i] == z[i]);
CuAssertIntEquals

2022-05-14 06:49 UTC, humleflue commented on c-svc23Vectors/types.h
> +#define TIME_SERIES_OBSERVATION_INIT_108_VALUES {1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2,
If this is only used in tests (which I assume), then please put it in the test file.

2022-05-14 06:51 UTC, humleflue commented
If you pull main, I think your pipeline will pass.

2022-05-15 11:01 UTC, humleflue commented on c-svc23Vectors/math.c
> +        }
Hvis det ikke er det her, som du vil, men at du gerne vil beholde dit sign, så synes jeg at det er super det her, men så må du gerne lige formatere det ordenligt 😉

2022-05-18 07:32 UTC, humleflue commented on c-svc23Vectors/math.c
> +double differencesSquared[TIME_SERIES_OBSERVATION_DIM];
Move this into absVariance and put a comment, that this was not transfered as a parameter as the Kin would not allow us to do so.

2022-05-18 09:16 UTC, humleflue approved these changes

2022-05-18 09:16 UTC, humleflue commented on c-svc23Vectors/math.c
> +    int smallestNumber = 999999;
Lav symbolsk konstant INT_MAX (behøver ikke at være INT_MAX men bare et stort tal)

2022-05-18 09:20 UTC, laurits-mumberg commented on c-svc23Vectors/math.c
> +    int smallestNumber = 999999;
DONE

2022-05-18 09:21 UTC, merged